import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="_hDsvS-x5GhYN8aT8uI8Uh_3MsDFVszbpMK76ugNYJI"></meta>
      <body className={inter.className}>{children}
      <Analytics/>
<SpeedInsights/>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NNH47JPV"
height="0" width="0"></iframe></noscript>
      </body>
    </html>
  );
}
